/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import javax.swing.JOptionPane;

/**
 *
 * @author J. Alfredo Brambila Hdez.
 */
public class JFrameMainMenu extends javax.swing.JFrame {

    /** Creates new form JFrameMainMenu */
    public JFrameMainMenu() {
        initComponents();
	this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonSimulador = new javax.swing.JButton();
        jButtonRecHospitalarios = new javax.swing.JButton();
        jButtonImpactoSE = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemVerRegiones = new javax.swing.JMenuItem();
        jMenuItemVerSegmentos = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemSalir = new javax.swing.JMenuItem();
        jMenuSimulador = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItemAsigRecursos = new javax.swing.JMenuItem();
        jMenuItemImpacto = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemAcercaDe = new javax.swing.JMenuItem();
        jMenuItemTemasAyuda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SEIMR/R-S - Menú Principal");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSimulador.setBackground(new java.awt.Color(75, 109, 140));
        jButtonSimulador.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSimulador.setText("Acceder");
        jButtonSimulador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSimuladorActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSimulador, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 120, -1));

        jButtonRecHospitalarios.setBackground(new java.awt.Color(75, 109, 140));
        jButtonRecHospitalarios.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRecHospitalarios.setText("Acceder");
        jButtonRecHospitalarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRecHospitalariosActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRecHospitalarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 120, -1));

        jButtonImpactoSE.setBackground(new java.awt.Color(75, 109, 140));
        jButtonImpactoSE.setForeground(new java.awt.Color(255, 255, 255));
        jButtonImpactoSE.setText("Acceder");
        jButtonImpactoSE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImpactoSEActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonImpactoSE, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 120, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/support/images/bkmenu.png"))); // NOI18N
        jPanel1.add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jMenu1.setText("Archivo");

        jMenuItemVerRegiones.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItemVerRegiones.setText("Ver Regiones");
        jMenuItemVerRegiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVerRegionesActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemVerRegiones);

        jMenuItemVerSegmentos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItemVerSegmentos.setText("Ver Segmentos");
        jMenuItemVerSegmentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVerSegmentosActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemVerSegmentos);
        jMenu1.add(jSeparator1);

        jMenuItemSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemSalir.setText("Salir");
        jMenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalirActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemSalir);

        jMenuBar1.add(jMenu1);

        jMenuSimulador.setText("Módulos");

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem4.setText("Simulador SEIMR/R-S");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenuSimulador.add(jMenuItem4);

        jMenuItemAsigRecursos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItemAsigRecursos.setText("Asignación de recursos");
        jMenuItemAsigRecursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAsigRecursosActionPerformed(evt);
            }
        });
        jMenuSimulador.add(jMenuItemAsigRecursos);

        jMenuItemImpacto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItemImpacto.setText("Impacto Socioeconómico");
        jMenuItemImpacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemImpactoActionPerformed(evt);
            }
        });
        jMenuSimulador.add(jMenuItemImpacto);

        jMenuBar1.add(jMenuSimulador);

        jMenu3.setText("Ayuda");

        jMenuItemAcercaDe.setText("Acerca de...");
        jMenuItemAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAcercaDeActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemAcercaDe);

        jMenuItemTemasAyuda.setText("Temas de ayuda");
        jMenuItemTemasAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTemasAyudaActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemTemasAyuda);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemImpactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemImpactoActionPerformed
        // TODO add your handling code here:
	JFrameImpactoSocioEconomico fme3 = new JFrameImpactoSocioEconomico();
	fme3.setVisible(true);
    }//GEN-LAST:event_jMenuItemImpactoActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
	JFrameSimulador fme1 = new JFrameSimulador();
	fme1.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItemAsigRecursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAsigRecursosActionPerformed
        // TODO add your handling code here:
	JFrameRecursosFSim fme2 = new JFrameRecursosFSim();
	fme2.setVisible(true);
    }//GEN-LAST:event_jMenuItemAsigRecursosActionPerformed

    private void jButtonSimuladorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSimuladorActionPerformed
        // TODO add your handling code here:
	JFrameSimulador fme1 = new JFrameSimulador();
	fme1.setVisible(true);
    }//GEN-LAST:event_jButtonSimuladorActionPerformed

    private void jButtonRecHospitalariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRecHospitalariosActionPerformed
        // TODO add your handling code here:
	JFrameRecursosFSim fme2 = new JFrameRecursosFSim();
	fme2.setVisible(true);
    }//GEN-LAST:event_jButtonRecHospitalariosActionPerformed

    private void jButtonImpactoSEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImpactoSEActionPerformed
        // TODO add your handling code here:
	JFrameImpactoSocioEconomico fme3 = new JFrameImpactoSocioEconomico();
	fme3.setVisible(true);
    }//GEN-LAST:event_jButtonImpactoSEActionPerformed

    private void jMenuItemVerRegionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVerRegionesActionPerformed
        // TODO add your handling code here:
	JFrameRegiones fme4 = new JFrameRegiones();
	fme4.setVisible(true);
    }//GEN-LAST:event_jMenuItemVerRegionesActionPerformed

    private void jMenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalirActionPerformed
        // TODO add your handling code here:
	System.exit(0);
    }//GEN-LAST:event_jMenuItemSalirActionPerformed

    private void jMenuItemVerSegmentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVerSegmentosActionPerformed
        // TODO add your handling code here:
	JFrameSegmentos fme5 = new JFrameSegmentos();
	fme5.setVisible(true);
    }//GEN-LAST:event_jMenuItemVerSegmentosActionPerformed

    private void jMenuItemAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAcercaDeActionPerformed
        // TODO add your handling code here:
	JFrameAcercaDe fme6 = new JFrameAcercaDe();
	fme6.setVisible(true);
    }//GEN-LAST:event_jMenuItemAcercaDeActionPerformed

    private void jMenuItemTemasAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTemasAyudaActionPerformed
        // TODO add your handling code here:
	JOptionPane.showMessageDialog(null, "No existen temas de ayuda por el momento", "Info", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItemTemasAyudaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonImpactoSE;
    private javax.swing.JButton jButtonRecHospitalarios;
    private javax.swing.JButton jButtonSimulador;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItemAcercaDe;
    private javax.swing.JMenuItem jMenuItemAsigRecursos;
    private javax.swing.JMenuItem jMenuItemImpacto;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JMenuItem jMenuItemTemasAyuda;
    private javax.swing.JMenuItem jMenuItemVerRegiones;
    private javax.swing.JMenuItem jMenuItemVerSegmentos;
    private javax.swing.JMenu jMenuSimulador;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables

}
