/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import domain.ModelSEIMRRS2;
import java.io.File;
import java.io.IOException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import optimization.TaskWorker;
import optimization.core.Problem;
import optimization.heuristics.Algorithm;
import optimization.heuristics.MoGeA;
import optimization.operators.Crossover;
import optimization.operators.Mutation;
import optimization.operators.impl.PolynomialMutation;
import optimization.operators.impl.SBXCrossover;
import optimization.problems.Covid19;
import optimization.problems.Covid19DR;
import org.apache.poi.openxml4j.exceptions.InvalidFormatException;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import tech.tablesaw.api.DoubleColumn;
import tech.tablesaw.api.Table;

/**
 *
 * @author J. Alfredo Brambila Hdez.
 */
public class JFrameAutoPamsM extends javax.swing.JDialog {

    JFrameSimulador parent;
    private Table originalData;
    private Covid19.SerieType _type;

    /**
     * Creates new form JFrameAutoPamsM
     */
    public JFrameAutoPamsM(JFrameSimulador p) {
        this.parent = p;
        initComponents();
        this.setLocationRelativeTo(null);
        this.setModal(true);
        for (int i = 0; i < 365; i++) {
            this.jComboDay.addItem("" + (i + 1));

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        gZetaI0 = new javax.swing.JTextField();
        gZetaI1 = new javax.swing.JTextField();
        gZetaI2 = new javax.swing.JTextField();
        gZetaI3 = new javax.swing.JTextField();
        gSigmaI3 = new javax.swing.JTextField();
        gSigmaI2 = new javax.swing.JTextField();
        gSigmaI1 = new javax.swing.JTextField();
        gSigmaI0 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        MIUUB = new javax.swing.JTextField();
        jTextFieldMIUN = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jRadioButtonDeath = new javax.swing.JRadioButton();
        jRadioButtonRecovery = new javax.swing.JRadioButton();
        jRadioButtonDR = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxD = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxR = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldIter = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldPob = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldExecutions = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jComboDay = new javax.swing.JComboBox<>();
        jTextFieldMAE = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextFieldPHIX0 = new javax.swing.JTextField();
        jTextFieldPHIX1 = new javax.swing.JTextField();
        jTextFieldPHIX2 = new javax.swing.JTextField();
        jTextFieldPHIX3 = new javax.swing.JTextField();

        buttonGroup2.add(jRadioButtonDeath);
        buttonGroup2.add(jRadioButtonRecovery);
        buttonGroup2.add(jRadioButtonDR);
        jRadioButtonDeath.setSelected(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Parámetros Generados"));

        jLabel1.setText("Registro:");

        jButton1.setText("Cargar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel5.setText("DELTXB");

        gZetaI0.setEditable(false);

        gZetaI1.setEditable(false);

        gZetaI2.setEditable(false);

        gZetaI3.setEditable(false);

        gSigmaI3.setEditable(false);

        gSigmaI2.setEditable(false);

        gSigmaI1.setEditable(false);

        gSigmaI0.setEditable(false);

        jLabel11.setText("ETAXB");

        jLabel12.setText("MIUUB");

        MIUUB.setEditable(false);

        jTextFieldMIUN.setEditable(false);
        jTextFieldMIUN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMIUNActionPerformed(evt);
            }
        });

        jLabel6.setText("MIUN");

        jRadioButtonDeath.setText("Muertes");

        jRadioButtonRecovery.setText("Recuperados");

        jRadioButtonDR.setText("M & R");

        jLabel7.setText("Optimizar:");

        jLabel8.setText("Muertes:");

        jComboBoxD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDActionPerformed(evt);
            }
        });

        jLabel9.setText("Recuperados:");

        jButton4.setText("Optimizar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel2.setText("Iteraciones:");

        jTextFieldIter.setText("10");
        jTextFieldIter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIterActionPerformed(evt);
            }
        });

        jLabel3.setText("Poblacion:");

        jTextFieldPob.setText("100");

        jLabel4.setText("Ejecuciones:");

        jTextFieldExecutions.setText("10");

        jLabel10.setText("Dia de inicio:");

        jComboDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboDayActionPerformed(evt);
            }
        });

        jTextFieldMAE.setEditable(false);

        jLabel14.setText("Funcion de evaluacion:");

        jLabel24.setText("PHIX:");

        jTextFieldPHIX0.setEditable(false);

        jTextFieldPHIX1.setEditable(false);

        jTextFieldPHIX2.setEditable(false);

        jTextFieldPHIX3.setEditable(false);
        jTextFieldPHIX3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPHIX3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addGap(14, 14, 14)
                        .addComponent(jComboBoxD, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxR, 0, 184, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonDeath)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonRecovery)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonDR))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(157, 157, 157)
                                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldMIUN, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(gZetaI0, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(gZetaI1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(gZetaI2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(gZetaI3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(gSigmaI0, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextFieldPHIX0, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jTextFieldPHIX1)
                                                    .addComponent(gSigmaI1, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(gSigmaI2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(gSigmaI3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel2)
                                                    .addComponent(jLabel4)
                                                    .addComponent(jLabel10))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(jTextFieldIter)
                                                            .addComponent(jTextFieldExecutions, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel3)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jTextFieldPob, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(jComboDay, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel14)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldMAE, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addGap(179, 179, 179)
                                .addComponent(jTextFieldPHIX2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPHIX3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(MIUUB, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel8)
                    .addComponent(jComboBoxD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBoxR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonDeath)
                    .addComponent(jRadioButtonRecovery)
                    .addComponent(jRadioButtonDR)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(gZetaI0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gZetaI1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gZetaI2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gZetaI3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(gSigmaI0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gSigmaI1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gSigmaI2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gSigmaI3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(jTextFieldPHIX0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPHIX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPHIX2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPHIX3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldMIUN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldIter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldPob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldExecutions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jComboDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldMAE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(MIUUB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(jButton3))
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        /*
	MS 0.01
	GS 0.02439
	GZ 0.05182
         */
 /*this.jTextFieldMSigma.setText("0.01");
	this.jTextFieldGSigma.setText("0.02439");
	this.jTextFieldGZeta.setText("0.05182");*/
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("Data", "xlsx", "csv"));
        fileChooser.setAcceptAllFileFilterUsed(true);
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            if (selectedFile.getName().contains(".xlsx")) {
                try {
                    try (XSSFWorkbook workbook = new XSSFWorkbook(selectedFile)) {
                        Sheet sheet = workbook.getSheetAt(0);
                        originalData = Table.create(selectedFile.getName());
                        for (int i = 0; i < sheet.getLastRowNum(); i++) {
                            Row row = sheet.getRow(i);
                            for (int j = 0; j < sheet.getRow(0).getLastCellNum(); j++) {
                                if (i == 0) {
                                    originalData.addColumns(DoubleColumn.create(row.getCell(j).getStringCellValue()));
                                } else {
                                    DoubleColumn column = (DoubleColumn) originalData.column(j);
                                    column.append(row.getCell(j).getNumericCellValue());
                                }
                            }
                        }
                    }
                    jTextField1.setText(selectedFile.getName());
                    loadCombo();
                } catch (Exception ex) {
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(this, "Ocurrio un error al intentar leer el archivo: " + ex.getMessage(), "Error con el archivo de datos", JOptionPane.ERROR_MESSAGE);
                }
            } else if (selectedFile.getName().contains(".csv")) {
                try {
                    originalData = Table.read().csv(selectedFile);
                    jTextField1.setText(selectedFile.getAbsolutePath());
                    loadCombo();
                } catch (Exception ex) {
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(this, "Ocurrio un error al intentar leer el archivo: " + ex.getMessage(), "Error con el archivo de datos", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (taskWorker != null) {
            if (!taskWorker.isDone()) {
                int showConfirmDialog = JOptionPane.showConfirmDialog(this, "Existe aun ejecuciones pendientes, al salir se cancelaran. Esta seguro ? ");
                if (showConfirmDialog == JOptionPane.YES_OPTION) {
                    if (_type == Covid19.SerieType.DEATHS) {
                        this.parent.setParamsGUI(_type, gZetaI0.getText(), gZetaI1.getText(), gZetaI2.getText(), gZetaI3.getText(), gSigmaI0.getText(), gSigmaI1.getText(), gSigmaI2.getText(), gSigmaI3.getText(), MIUUB.getText());
                    } else if (_type == Covid19.SerieType.RECOVERY) {
                        this.parent.setParamsGUI(_type, gZetaI0.getText(), gZetaI1.getText(), gZetaI2.getText(), gZetaI3.getText(), gSigmaI0.getText(), gSigmaI1.getText(), gSigmaI2.getText(), gSigmaI3.getText(), jTextFieldPHIX0.getText(), jTextFieldPHIX1.getText(), jTextFieldPHIX2.getText(), jTextFieldPHIX3.getText(), jTextFieldMIUN.getText());
                    } else {
                        this.parent.setParamsGUI(_type, gZetaI0.getText(), gZetaI1.getText(), gZetaI2.getText(), gZetaI3.getText(), gSigmaI0.getText(), gSigmaI1.getText(), gSigmaI2.getText(), gSigmaI3.getText(), jTextFieldPHIX0.getText(), jTextFieldPHIX1.getText(), jTextFieldPHIX2.getText(), jTextFieldPHIX3.getText(), jTextFieldMIUN.getText(), MIUUB.getText());
                    }
                    taskWorker.cancel(true);
                    this.dispose();
                }
            } else {
                if (_type == Covid19.SerieType.DEATHS) {
                    this.parent.setParamsGUI(_type, gZetaI0.getText(), gZetaI1.getText(), gZetaI2.getText(), gZetaI3.getText(), gSigmaI0.getText(), gSigmaI1.getText(), gSigmaI2.getText(), gSigmaI3.getText(), MIUUB.getText());
                } else if (_type == Covid19.SerieType.RECOVERY) {
                    this.parent.setParamsGUI(_type, gZetaI0.getText(), gZetaI1.getText(), gZetaI2.getText(), gZetaI3.getText(), gSigmaI0.getText(), gSigmaI1.getText(), gSigmaI2.getText(), gSigmaI3.getText(), jTextFieldPHIX0.getText(), jTextFieldPHIX1.getText(), jTextFieldPHIX2.getText(), jTextFieldPHIX3.getText(), jTextFieldMIUN.getText());
                } else {
                    this.parent.setParamsGUI(_type, gZetaI0.getText(), gZetaI1.getText(), gZetaI2.getText(), gZetaI3.getText(), gSigmaI0.getText(), gSigmaI1.getText(), gSigmaI2.getText(), gSigmaI3.getText(), jTextFieldPHIX0.getText(), jTextFieldPHIX1.getText(), jTextFieldPHIX2.getText(), jTextFieldPHIX3.getText(), jTextFieldMIUN.getText(), MIUUB.getText());
                }
                this.dispose();
            }
        } else {
            if (_type == Covid19.SerieType.DEATHS) {
                this.parent.setParamsGUI(_type, gZetaI0.getText(), gZetaI1.getText(), gZetaI2.getText(), gZetaI3.getText(), gSigmaI0.getText(), gSigmaI1.getText(), gSigmaI2.getText(), gSigmaI3.getText(), MIUUB.getText());
            } else if (_type == Covid19.SerieType.RECOVERY) {
                this.parent.setParamsGUI(_type, gZetaI0.getText(), gZetaI1.getText(), gZetaI2.getText(), gZetaI3.getText(), gSigmaI0.getText(), gSigmaI1.getText(), gSigmaI2.getText(), gSigmaI3.getText(), jTextFieldPHIX0.getText(), jTextFieldPHIX1.getText(), jTextFieldPHIX2.getText(), jTextFieldPHIX3.getText(), jTextFieldMIUN.getText());
            } else {
                this.parent.setParamsGUI(_type, gZetaI0.getText(), gZetaI1.getText(), gZetaI2.getText(), gZetaI3.getText(), gSigmaI0.getText(), gSigmaI1.getText(), gSigmaI2.getText(), gSigmaI3.getText(), jTextFieldPHIX0.getText(), jTextFieldPHIX1.getText(), jTextFieldPHIX2.getText(), jTextFieldPHIX3.getText(), jTextFieldMIUN.getText(), MIUUB.getText());
            }
            this.dispose();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (taskWorker != null) {
            if (!taskWorker.isDone()) {
                taskWorker.cancel(true);
            }
        }
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextFieldMIUNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMIUNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMIUNActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (originalData != null) {
            int population = Integer.parseInt(jTextFieldPob.getText());
            int iterations = Integer.parseInt(jTextFieldIter.getText());
            int executions = Integer.parseInt(jTextFieldExecutions.getText());
            population = Math.max(population, 2);
            iterations = Math.max(iterations, 1);
            executions = Math.max(executions, 1);
            Algorithm algorithm = null;
            Problem problem = null;
            _type = null;
            
            parent.modelo = new ModelSEIMRRS2();
            if (jRadioButtonDeath.isSelected()) {
                _type = Covid19.SerieType.DEATHS;
                problem = new Covid19(parent.modelo, parent.region, parent.estrato, parent.getjComboBoxEscenarios().getSelectedIndex(), originalData, jComboDay.getSelectedIndex(), jComboBoxD.getSelectedIndex(), _type);
            } else if (jRadioButtonRecovery.isSelected()) {
                _type = Covid19.SerieType.RECOVERY;
                problem = new Covid19(parent.modelo, parent.region, parent.estrato, parent.getjComboBoxEscenarios().getSelectedIndex(), originalData, jComboDay.getSelectedIndex(), jComboBoxR.getSelectedIndex(), _type);
            } else if (jRadioButtonDR.isSelected()) {
                _type = Covid19.SerieType.DEATHS_RECOVERY;
                problem = new Covid19DR(parent.modelo, parent.region, parent.estrato, parent.getjComboBoxEscenarios().getSelectedIndex(), originalData, jComboDay.getSelectedIndex(), jComboBoxD.getSelectedIndex(), jComboBoxR.getSelectedIndex());
            }
            Crossover crossover = new SBXCrossover(.9, 20);
            Mutation mutation = new PolynomialMutation();

            algorithm = new MoGeA(problem, population, iterations, 0.05, .25, crossover, mutation);

            if (taskWorker == null || taskWorker.isDone()) {
                if (_type == Covid19.SerieType.DEATHS) {
                    taskWorker = new TaskWorker(algorithm, executions, jTextFieldMAE, jProgressBar1, jButton4, gZetaI0, gZetaI1, gZetaI2, gZetaI3, gSigmaI0, gSigmaI1, gSigmaI2, gSigmaI3, MIUUB);
                    jTextFieldPHIX0.setText("");
                    jTextFieldPHIX1.setText("");
                    jTextFieldPHIX2.setText("");
                    jTextFieldPHIX3.setText("");
                    jTextFieldMIUN.setText("");
                } else if (_type == Covid19.SerieType.RECOVERY) {
                    taskWorker = new TaskWorker(algorithm, executions, jTextFieldMAE, jProgressBar1, jButton4, gZetaI0, gZetaI1, gZetaI2, gZetaI3, gSigmaI0, gSigmaI1, gSigmaI2, gSigmaI3, jTextFieldPHIX0, jTextFieldPHIX1, jTextFieldPHIX2, jTextFieldPHIX3, jTextFieldMIUN);
                    MIUUB.setText("");
                } else {
                    taskWorker = new TaskWorker(algorithm, executions, jTextFieldMAE, jProgressBar1, jButton4, gZetaI0, gZetaI1, gZetaI2, gZetaI3, gSigmaI0, gSigmaI1, gSigmaI2, gSigmaI3, jTextFieldPHIX0, jTextFieldPHIX1, jTextFieldPHIX2, jTextFieldPHIX3, MIUUB, jTextFieldMIUN);
                }

                taskWorker.execute();

            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBoxDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxDActionPerformed

    private void jTextFieldIterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIterActionPerformed

    private void jComboDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboDayActionPerformed

    private void jTextFieldPHIX3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPHIX3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPHIX3ActionPerformed
    public Table readExcelData(File file) throws IOException, InvalidFormatException {
        XSSFWorkbook workbook = new XSSFWorkbook(file);
        Sheet sheet = workbook.getSheetAt(0);
        Table table = Table.create(file.getName());
        for (int i = 0; i < sheet.getLastRowNum(); i++) {
            Row row = sheet.getRow(i);
            for (int j = 0; j < 10; j++) {
                if (i == 0) {
                    table.addColumns(DoubleColumn.create(row.getCell(j).getStringCellValue()));
                } else {
                    DoubleColumn column = (DoubleColumn) table.column(j);
                    column.append(row.getCell(j).getNumericCellValue());
                }
            }
        }
        workbook.close();
        return table;
    }

    protected TaskWorker taskWorker;


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField MIUUB;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField gSigmaI0;
    private javax.swing.JTextField gSigmaI1;
    private javax.swing.JTextField gSigmaI2;
    private javax.swing.JTextField gSigmaI3;
    private javax.swing.JTextField gZetaI0;
    private javax.swing.JTextField gZetaI1;
    private javax.swing.JTextField gZetaI2;
    private javax.swing.JTextField gZetaI3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBoxD;
    private javax.swing.JComboBox<String> jComboBoxR;
    private javax.swing.JComboBox<String> jComboDay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JRadioButton jRadioButtonDR;
    private javax.swing.JRadioButton jRadioButtonDeath;
    private javax.swing.JRadioButton jRadioButtonRecovery;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldExecutions;
    private javax.swing.JTextField jTextFieldIter;
    private javax.swing.JTextField jTextFieldMAE;
    private javax.swing.JTextField jTextFieldMIUN;
    private javax.swing.JTextField jTextFieldPHIX0;
    private javax.swing.JTextField jTextFieldPHIX1;
    private javax.swing.JTextField jTextFieldPHIX2;
    private javax.swing.JTextField jTextFieldPHIX3;
    private javax.swing.JTextField jTextFieldPob;
    // End of variables declaration//GEN-END:variables

    private void loadCombo() {
        String[] columnNames = originalData.columnNames().toArray(new String[originalData.columnNames().size()]);
        jComboBoxD.setModel(new DefaultComboBoxModel<>(columnNames));
        jComboBoxR.setModel(new DefaultComboBoxModel<>(columnNames));
        for (int i = 0; i < columnNames.length; i++) {
            String columnName = columnNames[i];
            if (columnName.contains("R")) {
                jComboBoxR.setSelectedIndex(i);
            } else if (columnName.contains("D")) {
                jComboBoxD.setSelectedIndex(i);
            }
        }
        jComboDay.setEnabled(originalData.rowCount() != 365);
        if (originalData.rowCount() == 365) {
            jComboDay.setSelectedIndex(0);
        }
        if (jComboBoxD.getModel().getSize() > 0 && jComboBoxD.getSelectedIndex() == -1) {
            jComboBoxD.setSelectedIndex(0);
            jComboBoxR.setSelectedIndex(0);
        }
    }

}
