/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;

/**
 *
 * @author J. Alfredo Brambila Hdez.
 */
public class JFrameSplash extends javax.swing.JFrame implements Runnable {

    Thread t;
    
    /** Creates new form JFrameSplash */
    public JFrameSplash() {
        initComponents();
	try {
	//UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
	//UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
	} catch(Exception e) {
	    
	}
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelBackG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabelBackG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/support/images/splash002.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelBackG)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelBackG)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelBackG;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
	 try {
            this.setLocationRelativeTo(null);
            this.setVisible(true);
            //this.setUndecorated(true);
            //setBackground(new Color(1.0f,1.0f,1.0f,0.0f));
            t.sleep(3000);
            this.dispose();
	    JFrameMainMenu v1 = new JFrameMainMenu();
	    v1.setVisible(true);
            //new JFrameMenuPrincipal.setVisible(true);
        } catch (InterruptedException ex) {
            Logger.getLogger(JFrameSplash.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}
